package constant

type EndpointType string

const (
	EndpointTypeOpenAI                EndpointType = "openai"
	EndpointTypeOpenAIResponse        EndpointType = "openai-response"
	EndpointTypeOpenAIResponseCompact EndpointType = "openai-response-compact"
	EndpointTypeAnthropic             EndpointType = "anthropic"
	EndpointTypeGemini                EndpointType = "gemini"
	EndpointTypeGeminiEmbedding       EndpointType = "gemini-embedding"
	EndpointTypeJinaRerank            EndpointType = "jina-rerank"
	EndpointTypeImageGeneration       EndpointType = "image-generation"
	EndpointTypeEmbeddings            EndpointType = "embeddings"
	EndpointTypeOpenAIVideo           EndpointType = "openai-video"
	EndpointTypeAudio                 EndpointType = "audio"
	EndpointTypeAudioTTS              EndpointType = "audio-tts"
	EndpointTypeAudioSTT              EndpointType = "audio-stt"
	EndpointTypeAudioSpeechToSpeech   EndpointType = "audio-speech-to-speech"
	EndpointTypeAudioSFX              EndpointType = "audio-sfx"
	EndpointTypeAudioMusic            EndpointType = "audio-music"
	EndpointTypeAudioIsolation        EndpointType = "audio-isolation"
	EndpointTypeAudioAlignment        EndpointType = "audio-alignment"
	EndpointTypeModel3D               EndpointType = "model-3d"
	EndpointTypeModel3DText           EndpointType = "model-3d-text"
	EndpointTypeModel3DImage          EndpointType = "model-3d-image"
	EndpointTypeModel3DMultiImage     EndpointType = "model-3d-multi-image"
	EndpointTypeModel3DPostProcess    EndpointType = "model-3d-post-process"
	EndpointTypeModel3DAnimation      EndpointType = "model-3d-animation"
	EndpointTypeModel3DRemesh         EndpointType = "model-3d-remesh"
	EndpointTypeModel3DConvert        EndpointType = "model-3d-convert"
	EndpointTypeModel3DResize         EndpointType = "model-3d-resize"
	EndpointTypeModel3DRetexture      EndpointType = "model-3d-retexture"
	EndpointTypeModel3DRigging        EndpointType = "model-3d-rigging"
	EndpointTypeModel3DCharacterAnim  EndpointType = "model-3d-character-animation"
	//EndpointTypeMidjourney     EndpointType = "midjourney-proxy"
	//EndpointTypeSuno           EndpointType = "suno-proxy"
	//EndpointTypeKling          EndpointType = "kling"
	//EndpointTypeJimeng         EndpointType = "jimeng"
)
